settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: LernGo
  path: B:\Gocode\LernGo
  args:
  - main.go
  commands:
    fmt:
      status: true
    # build:
    #   status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
